version: '3.8'
services:
  postgres:
    image: postgres:16.1-alpine
    restart: on-failure
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: simpliz
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: devsecret
